application: avatar-generator
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /img
  static_dir: img

- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /(.*\.(gif|png|jpg|ico))
  static_files: \1
  upload: .*\.(gif|png|jpg|ico)  

- url: /.*
  script: index.html
  
skip_files:

- ^.+\.(bak|cmd|db|yaml)$
- ^(.*/)?\.(bak|cmd|db|yaml)$
- ^~.*$
- ^(.*/)?~.*$